package gov.nih.nci.caintegrator.dto.query;


/**
 * @author BhattarR
 */
public enum QueryType {
	GENE_EXPR_QUERY_TYPE,
    UNIFIED_GENE_EXPR_QUERY_TYPE,
    CGH_QUERY_TYPE,
	CLINICAL_DATA_QUERY_TYPE,
	CLASS_COMPARISON_QUERY,
	PCA_QUERY,
	HC_QUERY,
	GENE_QUERY_FOR_HOA,
	PROBESET_CLONEID_QUERY_FOR_HOA,
	SNP_QUERY_FOR_HOA,;
	
}
